// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaw           float32                `protobuf:"fixed32,1,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          float32                `protobuf:"fixed32,3,opt,name=roll,proto3" json:"roll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rotation) Reset() {
	*x = Rotation{}
	mi := &file_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rotation) ProtoMessage() {}

func (x *Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rotation.ProtoReflect.Descriptor instead.
func (*Rotation) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Rotation) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *Rotation) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *Rotation) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	OwnerAddress  string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Position      *Vector3               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"` // WGS-84 (Lat/Lon/Alt)
	Rotation      *Rotation              `protobuf:"bytes,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity      *Vector3               `protobuf:"bytes,6,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *EntityState) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityState) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityState) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *EntityState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityState) GetRotation() *Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *EntityState) GetVelocity() *Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityState) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EntityBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityBatch) Reset() {
	*x = EntityBatch{}
	mi := &file_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityBatch) ProtoMessage() {}

func (x *EntityBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityBatch.ProtoReflect.Descriptor instead.
func (*EntityBatch) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *EntityBatch) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneIds       []string               `protobuf:"bytes,1,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

type WorldEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ZoneId        string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldEvent) Reset() {
	*x = WorldEvent{}
	mi := &file_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEvent) ProtoMessage() {}

func (x *WorldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEvent.ProtoReflect.Descriptor instead.
func (*WorldEvent) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *WorldEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WorldEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WorldEvent) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *WorldEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorldEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PhygitalTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Location      *Vector3               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhygitalTrigger) Reset() {
	*x = PhygitalTrigger{}
	mi := &file_proto_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhygitalTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhygitalTrigger) ProtoMessage() {}

func (x *PhygitalTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhygitalTrigger.ProtoReflect.Descriptor instead.
func (*PhygitalTrigger) Descriptor() ([]byte, []int) {
	return file_proto_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *PhygitalTrigger) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *PhygitalTrigger) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PhygitalTrigger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhygitalTrigger) GetLocation() *Vector3 {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *PhygitalTrigger) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PhygitalTrigger) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_bridge_proto protoreflect.FileDescriptor

const file_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\x12proto/bridge.proto\x12\x06bridge\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"F\n" +
	"\bRotation\x12\x10\n" +
	"\x03yaw\x18\x01 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x02R\x05pitch\x12\x12\n" +
	"\x04roll\x18\x03 \x01(\x02R\x04roll\"\xb2\x02\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\x12+\n" +
	"\bposition\x18\x04 \x01(\v2\x0f.bridge.Vector3R\bposition\x12,\n" +
	"\brotation\x18\x05 \x01(\v2\x10.bridge.RotationR\brotation\x12+\n" +
	"\bvelocity\x18\x06 \x01(\v2\x0f.bridge.Vector3R\bvelocity\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\">\n" +
	"\vEntityBatch\x12/\n" +
	"\bentities\x18\x01 \x03(\v2\x13.bridge.EntityStateR\bentities\"-\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bzone_ids\x18\x01 \x03(\tR\azoneIds\"\xb3\x01\n" +
	"\n" +
	"WorldEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc3\x02\n" +
	"\x0fPhygitalTrigger\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12+\n" +
	"\blocation\x18\x04 \x01(\v2\x0f.bridge.Vector3R\blocation\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.bridge.PhygitalTrigger.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x97\x01\n" +
	"\rBridgeService\x12C\n" +
	"\x13StreamEntityUpdates\x12\x13.bridge.EntityState\x1a\x13.bridge.EntityBatch(\x010\x01\x12A\n" +
	"\x0fSubscribeEvents\x12\x18.bridge.SubscribeRequest\x1a\x12.bridge.WorldEvent0\x01B;Z9github.com/YouKnowZo/Meta_The_World/services/bridge/protob\x06proto3"

var (
	file_proto_bridge_proto_rawDescOnce sync.Once
	file_proto_bridge_proto_rawDescData []byte
)

func file_proto_bridge_proto_rawDescGZIP() []byte {
	file_proto_bridge_proto_rawDescOnce.Do(func() {
		file_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)))
	})
	return file_proto_bridge_proto_rawDescData
}

var file_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bridge_proto_goTypes = []any{
	(*Vector3)(nil),               // 0: bridge.Vector3
	(*Rotation)(nil),              // 1: bridge.Rotation
	(*EntityState)(nil),           // 2: bridge.EntityState
	(*EntityBatch)(nil),           // 3: bridge.EntityBatch
	(*SubscribeRequest)(nil),      // 4: bridge.SubscribeRequest
	(*WorldEvent)(nil),            // 5: bridge.WorldEvent
	(*PhygitalTrigger)(nil),       // 6: bridge.PhygitalTrigger
	nil,                           // 7: bridge.PhygitalTrigger.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_bridge_proto_depIdxs = []int32{
	0,  // 0: bridge.EntityState.position:type_name -> bridge.Vector3
	1,  // 1: bridge.EntityState.rotation:type_name -> bridge.Rotation
	0,  // 2: bridge.EntityState.velocity:type_name -> bridge.Vector3
	8,  // 3: bridge.EntityState.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 4: bridge.EntityBatch.entities:type_name -> bridge.EntityState
	8,  // 5: bridge.WorldEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: bridge.PhygitalTrigger.location:type_name -> bridge.Vector3
	7,  // 7: bridge.PhygitalTrigger.metadata:type_name -> bridge.PhygitalTrigger.MetadataEntry
	8,  // 8: bridge.PhygitalTrigger.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 9: bridge.BridgeService.StreamEntityUpdates:input_type -> bridge.EntityState
	4,  // 10: bridge.BridgeService.SubscribeEvents:input_type -> bridge.SubscribeRequest
	3,  // 11: bridge.BridgeService.StreamEntityUpdates:output_type -> bridge.EntityBatch
	5,  // 12: bridge.BridgeService.SubscribeEvents:output_type -> bridge.WorldEvent
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_bridge_proto_init() }
func file_proto_bridge_proto_init() {
	if File_proto_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bridge_proto_rawDesc), len(file_proto_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bridge_proto_goTypes,
		DependencyIndexes: file_proto_bridge_proto_depIdxs,
		MessageInfos:      file_proto_bridge_proto_msgTypes,
	}.Build()
	File_proto_bridge_proto = out.File
	file_proto_bridge_proto_goTypes = nil
	file_proto_bridge_proto_depIdxs = nil
}
